api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls")),
    path('onSpot/', include("onSpot.urls"))
]

blog/urls.py
from django.urls import path

from . import views

app_name="blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.entry, name="entry")
]

onSpot/urls.py
from django.urls import path

from . import views

app_name='onSpot'
urlpatterns=[
    path('', views.index, name='index'),
    path('auth', views.auth, name='auth'),
    path('playlists/<str:playlist_id>/', views.playlists, name="playlists")
]

blog/models.py
from django.db import models

class Entry(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=100)
    pub_date = models.DateTimeField("date_published")
    author = models.CharField(max_length=50)
    content = models.TextField()
    def __str__(self):
        return self.title

# Create your models here.

onSpot/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import get_object_or_404

from .models import Entry
from api.decorators import json_or_template

@json_or_template('blog/index.html')
def index(request):
    entries = Entry.objects.all().order_by('-pub_date')
    # TODO: order by, clean data
    return entries

@json_or_template('blog/entry.html')
def entry(request, pk):
    result = get_object_or_404(Entry, pk=pk)
    return result

onSpot/views.py
import os
import json
import requests

from django.shortcuts import render, redirect

from .spotify import Spotify

def index(request):
    playlists = Spotify(request).get(
        'https://api.spotify.com/v1/me/playlists'
    )
    return render(request, 'onSpot/index.html', {'data': playlists})

def auth(request):
    client_id = os.getenv('SPOTIFY_ID')
    scope=' '.join([
        'user-read-private', 
        'user-read-email', 
        'playlist-read-private',
        'user-library-read', 
        'playlist-read-collaborative'
    ])
    redirect_uri=os.getenv('BASE_URL') + '/onSpot/'

    return redirect(f'https://accounts.spotify.com/authorize?response_type=code&client_id={client_id}&scope={scope}&redirect_uri={redirect_uri}')

# @spotify_authentication()
def playlists(request, playlist_id):
    # playlist = spotify(request, requests.get, f'https://api.spotify.com/v1/playlists/{playlist_id}/tracks')
    playlist = Spotify(request).get(f'https://api.spotify.com/v1/playlists/{playlist_id}/tracks')    
    return render(request, 'onSpot/playlists.html', {'playlist': playlist})

# @spotify_authentication()
def liked_songs(request):
    Spotify(request).get(
        request,
        request.get,
        'https://api.spotify.com/v1/me/tracks'
    )

blog/templates/blog/entry.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{output.title}}</title>    
    </head>
    <body>
        <a href="{% url 'blog:index' %}">back to all entries</a>
        <h2>{{output.title}}</h2>
        <h3>{{output.subtitle}}</h4>
        <p>{{output.content}}</p>
        <p> 
            - {{output.author}}<br/>
            {{output.pub_date}}
        </p>
    </body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Greyson's Blog</title>
    </head>
    <body>
        <h2>It's a Blog</h2>
        {% if output %}
        <table>
            {% for entry in output %}
            <tr>
                <td>
                    <a href="{% url 'blog:entry' entry.id %}">
                        <h3>{{ entry.title }}</h3>
                    </a>
                </td>
                <td><h4>| {{ entry.subtitle }} | </h4></td>
                <td>{{ entry.pub_date }} </td>
            </tr>
            {% endfor %}
        <table>
        {% else %}
        <p>It doesn't have any entries yet though</p>
        {% endif %}
    </body>
</html>

onSpot/templates/onSpot/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>onSpot</title>
    </head>
    <body>
        <h1>onSpot</h1>
        <table>
            <tbody>
                <thead>
                    <tr>
                        <td></td>
                        <td>Playlist</td>
                        <td>Public</td>
                        <td>Songs</td>
                        <td>Author</td>
                    </tr>
                </thead>
                {% for item in data.items %}
                <tr>
                    <td>
                        <img src="{{ item.images.1.url }}" width="60px" height = "60px"/>
                    </td>
                    <td><a href="playlists/{{ item.id }}" >{{ item.name }}</a></td>
                    <td>{{ item.tracks.total }}</td>
                    <td><input type="checkbox" checked={{item.public}} /></td>
                    <td>{{ item.owner.display_name }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </body>
</html>

onSpot/templates/onSpot/playlists.html
<h1>Playlist</h1>

<table>
    <thead>

    </thead>
    <tbody>
        {% for item in playlist.items %}
        <tr>
            <td>{{item.track.name}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>